### ISSUE TITLE
Framework name

### ISSUE THREAD

**Issue by ptclarke** [jrendel/SwiftKeychainWrapper#17]
My understanding is convention dictates this should be in the form XXXKeyChainWrapper where XXX is a unique prefix associated with the developer. While the name as it stands is descriptive it is not conventional. Really nice piece of code and would like to be able to use it but site naming conventions preclude this, any chance you will consider renaming it?

**Comment by jrendel** [comment]
I know the convention of prefixing in objective c came about because of the lack of namespaces. This is no longer an issue in Swift. So I'm not sure how I feel about this. I like the clean name, "SwiftKeycahinWrapper". I felt the prefixes people had to use were odd.  Is there a reason you can't use it without a prefix other than not following the objective c convention?

If it makes the library more useful for people, I would consider possibly adding a prefix. However, when you look at other popular libraries, such as Alamofire, they aren't using prefixes either.

**Comment by ptclarke** [comment]
Thanks for the response, your point of view is valid, and if you do not see the need to stick with prefixing that is fine.

For us the prefix is a question of site standards, possibly falling a bit behind the times except that we expect to be bridging Swift and ObjC for some time to come, also expect Apple to maintain the naming standard for new frameworks and libraries in Swift as they need to be unique in a project/ workspace.
As a side note, in the case of Alamofire that is Matt Thompson’s company name as well as a wild flower in Texas so it is not a generic name and less likely to conflict with other frameworks; that said, being prefix fixated as I am I do struggle with it a bit.
