### ISSUE TITLE
cocoapods version update

### ISSUE THREAD

**Issue by shashankcodes** [jrendel/SwiftKeychainWrapper#63]
The current version (2.2.0) has not been updated on cocoapods (https://cocoapods.org/pods/SwiftKeychainWrapper) and cannot be installed using pods for now. Please update the version from 2.0 to 2.2 over there.

**Comment by jrendel** [comment]
I have been having some issues with the CocoaPod update tool accepting my latest changes. I still need to figure that out, for now you can point your pod file directly at the master branch:

pod 'SwiftKeychainWrapper', :git => 'https://github.com/jrendel/SwiftKeychainWrapper.git', :branch => 'master'

**Comment by JRG-Developer** [comment]
In order to use CocoaPods with Swift 3.0, you must currently do the following:

(1) Create a `.swift_version` file with just the text `3.0`. Save this file in the same directory as your pod spec.

(2) Use CocoaPods version `1.1.0.rc.2`. You can verify your CocoaPods version using the command `pod --version`.

For more details, see this issue:
https://github.com/CocoaPods/CocoaPods/pull/5841

After doing/confirming the above, you should be able to push to trunk.

Any issues, let me know, and I'm happy to help. :]

**Comment by jrendel** [comment]
I tried this earlier this week but had no luck. Setup the .swift_version file and using the latest pre release of CocoaPods. I'll look into it again this weekend and see if I can get it sorted out. 

I know even after doing these steps, when trying to push to trunk I was still getting an error related to the Use Legacy Swift setting. Since my library is on Swift 3 I had that set to No. Do you know if that is correct or does it need to be something different?

**Comment by shashankcodes** [comment]
Try making it as unspecified and push if it works. The bolts-swift framework I use gives me unspecified when i install it using pods.

**Comment by JRG-Developer** [comment]
`Try making it as unspecified and push if it works. The bolts-swift framework I use gives me unspecified when i install it using pods.`

^ AFAICT, this is a bug in how CocoaPods sets up the pods frameworks... you can't "set as unspecified" using any syntax in the pod spec, and even if you could, XCode wouldn't understand it... as you've likely found, Xcode _insists_ on setting this before it will let you build, right? ;)

**Comment by JRG-Developer** [comment]
`Since my library is on Swift 3 I had that set to No.`

^ CocoaPods actually creates the pod framework when it's linting... in my own tests, I've been able to push to a _private_ repository (uses same lint, AFAIK) by including the `.swift_version`, which tells it how to set the `swift legacy version`.

In other words, you _have_ to create the `.swift_version` file... CocoaPods isn't smart enough (yet) to pick up on your project settings.

BTW, this fixes _linting_, but I don't thinking `pod install` has been fixed...? If you guys find out I'm wrong here, please let me know... I'm currently using a post install strict to set it... for example, see

http://blog.bitrise.io/2016/09/17/cocoapods-issue-and-fix-with-xcode-8.html

**Comment by jrendel** [comment]
I also noticed on my test project using pod install / pod update with the new pre-release of CocoaPods was messing things up as well. Something I was doing was actually changing my local repo's url to point to the Cocoapods spec repo. It was really strange...and then telling me I had like 2000 updates to pull.

Then I made a mistake on correcting that repo url and pointed it to the SwiftKeychainWrapper GitHub repo instead of SwiftKeychainWrapperExample...so my repos are a bit of a mess now as well and I need to do some clean up.

**Comment by jrendel** [comment]
Alright, so after seeing multiple weird issues on my end, I went back to square one, wiping everything, and updating rvm and ruby (both of which were on really old versions). Re-installing Cocoapods pre release and I was finally able to get everything to work. The Cocoapod library should now be on 2.2.0 of SwiftKeychainWrapper.

**Comment by JRG-Developer** [comment]
👍 Awesome! Thanks.
